// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlyJ2sVcyFel5kFs_sIvwMWTaCA7w1yIA',
    appId: '1:953553134553:web:0ccf60c26a5a8c854bafc8',
    messagingSenderId: '953553134553',
    projectId: 'forlong-5d60d',
    authDomain: 'forlong-5d60d.firebaseapp.com',
    storageBucket: 'forlong-5d60d.firebasestorage.app',
    measurementId: 'G-ZJ1LM1FMF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6P2zOF4JNWaxMBZI8GAZxU2uP97XARAA',
    appId: '1:953553134553:android:3902cd38b6c749554bafc8',
    messagingSenderId: '953553134553',
    projectId: 'forlong-5d60d',
    storageBucket: 'forlong-5d60d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyChsi_i5Zld8MioW_ZovAmqiOM6WoyNk',
    appId: '1:953553134553:ios:75077d972d8037fb4bafc8',
    messagingSenderId: '953553134553',
    projectId: 'forlong-5d60d',
    storageBucket: 'forlong-5d60d.firebasestorage.app',
    iosBundleId: 'com.example.forlong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyChsi_i5Zld8MioW_ZovAmqiOM6WoyNk',
    appId: '1:953553134553:ios:75077d972d8037fb4bafc8',
    messagingSenderId: '953553134553',
    projectId: 'forlong-5d60d',
    storageBucket: 'forlong-5d60d.firebasestorage.app',
    iosBundleId: 'com.example.forlong',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlyJ2sVcyFel5kFs_sIvwMWTaCA7w1yIA',
    appId: '1:953553134553:web:d4abb0bcb1dffc424bafc8',
    messagingSenderId: '953553134553',
    projectId: 'forlong-5d60d',
    authDomain: 'forlong-5d60d.firebaseapp.com',
    storageBucket: 'forlong-5d60d.firebasestorage.app',
    measurementId: 'G-3HLECVQZ50',
  );

}